services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imr-app
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONUNBUFFERED: "1"
    ports:
      - "8000:8000"  
    stdin_open: true
    tty: true
